// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dajaypvtngtognutjzhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhamF5cHZ0bmd0b2dudXRqemhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NjMyOTksImV4cCI6MjA2NDEzOTI5OX0.eNqH6huA--NhBDd_iKPiqhqrUXCBA_DeaAYLnAgNM1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);