// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwzeyueckaafxgaffjpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3emV5dWVja2FhZnhnYWZmanByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NzE1NTQsImV4cCI6MjA2NDE0NzU1NH0.wFcmT3aBnSqnsJNb6HbEI23DTYZ09sr6lCm90zdAIgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);